[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
resource_manager = "CcvkCG2poiGbhLzkodhefhJbMbBW9AxHdKPR3eHrxfvf"
item_nft = "6wUan26ACFhc3DhFPWh3K3QGxhHMAubKAyUtqRfJz9ej"
crafting = "GqTny3DGUaCXESufnpUQXG1p8QFodc1aCrYG1qvPkqXd"
search = "3kx233sHmZfTrMHJ66sqBip2nAqntfL6y6V219BfmBdN"
marketplace = "xCeFkpeadNjjYyL3BStmgDceC9ZjeRW3DtErAJ1nQ2y"
magic_token = "2ug8zVrkg3zkpCqEuR4AR2KBEkhSLr49pbcScTLrDKTL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
