[package]
name = "search"
version = "0.1.0"
description = "Resource search logic with cooldown for Kozatskyi Biznes"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "search"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
default = []

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
game_core = { path = "../../crates/game_core" }
resource_manager = { path = "../resource_manager", features = ["cpi"] }
