[package]
name = "magic_token"
version = "0.1.0"
description = "Magic token mint controls for Kozatskyi Biznes"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "magic_token"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }

